export const amoledLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '909090', fontStyle: 'italic' },
        { token: 'keyword', foreground: '1a5cff' },
        { token: 'string', foreground: '008800' },
        { token: 'number', foreground: '906020' },
        { token: 'type', foreground: '7040c0' },
        { token: 'function', foreground: '1a5cff' },
        { token: 'variable', foreground: '1a1a1a' },
        { token: 'operator', foreground: '606060' },
        { token: 'delimiter', foreground: '606060' },
        { token: 'tag', foreground: 'cc0000' },
        { token: 'attribute.name', foreground: '7040c0' },
        { token: 'attribute.value', foreground: '008800' },
      ],
      colors: {
        'editor.background': '#f5f5f5',
        'editor.foreground': '#1a1a1a',
        'editor.lineHighlightBackground': '#eeeeee',
        'editor.selectionBackground': '#1a5cff28',
        'editorCursor.foreground': '#1a5cff',
        'editorLineNumber.foreground': '#b0b0b0',
        'editorLineNumber.activeForeground': '#606060',
        'editor.inactiveSelectionBackground': '#1a5cff12',
        'editorIndentGuide.background': '#e8e8e8',
        'editorIndentGuide.activeBackground': '#d0d0d0',
        'editorBracketMatch.background': '#1a5cff18',
        'editorBracketMatch.border': '#1a5cff33',
        'editorGutter.background': '#f5f5f5',
        'scrollbar.shadow': '#0000',
        'scrollbarSlider.background': '#00000012',
        'scrollbarSlider.hoverBackground': '#00000020',
        'scrollbarSlider.activeBackground': '#00000030',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#d0d0d0',
        'editorSuggestWidget.selectedBackground': '#1a5cff18',
      },
};
