export const amoledTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '505050', fontStyle: 'italic' },
        { token: 'keyword', foreground: '4f8cff' },
        { token: 'string', foreground: '44ff44' },
        { token: 'number', foreground: 'ff8844' },
        { token: 'type', foreground: 'ffcc44' },
        { token: 'function', foreground: '4f8cff' },
        { token: 'variable', foreground: 'e0e0e0' },
        { token: 'operator', foreground: '808080' },
        { token: 'delimiter', foreground: '808080' },
        { token: 'tag', foreground: 'ff4444' },
        { token: 'attribute.name', foreground: 'a78bfa' },
        { token: 'attribute.value', foreground: '44ff44' },
      ],
      colors: {
        'editor.background': '#000000',
        'editor.foreground': '#e0e0e0',
        'editor.lineHighlightBackground': '#050505',
        'editor.selectionBackground': '#4f8cff28',
        'editorCursor.foreground': '#4f8cff',
        'editorLineNumber.foreground': '#303030',
        'editorLineNumber.activeForeground': '#505050',
        'editor.inactiveSelectionBackground': '#4f8cff12',
        'editorIndentGuide.background': '#0a0a0a',
        'editorIndentGuide.activeBackground': '#151515',
        'editorBracketMatch.background': '#4f8cff18',
        'editorBracketMatch.border': '#4f8cff33',
        'editorGutter.background': '#000000',
        'scrollbar.shadow': '#0000',
        'scrollbarSlider.background': '#ffffff06',
        'scrollbarSlider.hoverBackground': '#ffffff0a',
        'scrollbarSlider.activeBackground': '#ffffff14',
        'editorWidget.background': '#0a0a0a',
        'editorSuggestWidget.background': '#0a0a0a',
        'editorSuggestWidget.border': '#ffffff08',
        'editorSuggestWidget.selectedBackground': '#4f8cff18',
      },
};
