export const ayuLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '8994a6', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'ff6906' },
        { token: 'string', foreground: '6c9a4e' },
        { token: 'number', foreground: 'e6892e' },
        { token: 'type', foreground: '41a6c2' },
        { token: 'function', foreground: '55b5db' },
        { token: 'variable', foreground: '5c6773' },
        { token: 'operator', foreground: 'f29668' },
        { token: 'delimiter', foreground: 'f29668' },
        { token: 'tag', foreground: '41a6c2' },
        { token: 'attribute.name', foreground: 'ff6906' },
        { token: 'attribute.value', foreground: '6c9a4e' },
      ],
      colors: {
        'editor.background': '#fafafa',
        'editor.foreground': '#5c6773',
        'editor.lineHighlightBackground': '#f0f0f0',
        'editorCursor.foreground': '#41a6c2',
        'editorLineNumber.foreground': '#b0b8c4',
        'editorLineNumber.activeForeground': '#8994a6',
        'editor.selectionBackground': '#e0e8ec',
        'editorIndentGuide.background': '#f0f0f0',
        'editorIndentGuide.activeBackground': '#e6e6e6',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#b0b8c4',
      },
};
