export const ayuTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '626a73', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'ff8f40' },
        { token: 'string', foreground: 'aad94c' },
        { token: 'number', foreground: 'e6b450' },
        { token: 'type', foreground: '59c2ff' },
        { token: 'function', foreground: 'ffb454' },
        { token: 'variable', foreground: 'e6e1cf' },
        { token: 'operator', foreground: 'f29668' },
        { token: 'delimiter', foreground: 'f29668' },
        { token: 'tag', foreground: '39bae6' },
        { token: 'attribute.name', foreground: 'ff8f40' },
        { token: 'attribute.value', foreground: 'aad94c' },
      ],
      colors: {
        'editor.background': '#0a0e14',
        'editor.foreground': '#e6e1cf',
        'editor.lineHighlightBackground': '#0f1419',
        'editorCursor.foreground': '#39bae6',
        'editorLineNumber.foreground': '#343f4b',
        'editorLineNumber.activeForeground': '#475866',
        'editor.selectionBackground': '#1a3a4a',
        'editorIndentGuide.background': '#0f1419',
        'editorIndentGuide.activeBackground': '#182028',
        'editorWidget.background': '#1a1f29',
        'editorSuggestWidget.background': '#1a1f29',
        'editorSuggestWidget.border': '#343f4b',
      },
};
