export const catppuccinTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'cba6f7' },
        { token: 'string', foreground: 'a6e3a1' },
        { token: 'number', foreground: 'fab387' },
        { token: 'type', foreground: 'f9e2af' },
        { token: 'function', foreground: '89b4fa' },
        { token: 'variable', foreground: 'cdd6f4' },
        { token: 'operator', foreground: '89dceb' },
        { token: 'delimiter', foreground: '89dceb' },
        { token: 'tag', foreground: 'f38ba8' },
        { token: 'attribute.name', foreground: 'cba6f7' },
        { token: 'attribute.value', foreground: 'a6e3a1' },
      ],
      colors: {
        'editor.background': '#1e1e2e',
        'editor.foreground': '#cdd6f4',
        'editor.lineHighlightBackground': '#2a2a3c',
        'editorCursor.foreground': '#89b4fa',
        'editorLineNumber.foreground': '#45475a',
        'editorLineNumber.activeForeground': '#585b70',
        'editor.selectionBackground': '#313244',
        'editorIndentGuide.background': '#2a2a3c',
        'editorIndentGuide.activeBackground': '#363648',
        'editorWidget.background': '#313244',
        'editorSuggestWidget.background': '#313244',
        'editorSuggestWidget.border': '#45475a',
      },
};
