export const catppuccinLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '7c7f93', fontStyle: 'italic' },
        { token: 'keyword', foreground: '8839ef' },
        { token: 'string', foreground: '40a02b' },
        { token: 'number', foreground: 'fe640b' },
        { token: 'type', foreground: 'df8e1d' },
        { token: 'function', foreground: '1e66f5' },
        { token: 'variable', foreground: '4c4f69' },
        { token: 'operator', foreground: '179299' },
        { token: 'delimiter', foreground: '179299' },
        { token: 'tag', foreground: 'd20f39' },
        { token: 'attribute.name', foreground: '8839ef' },
        { token: 'attribute.value', foreground: '40a02b' },
      ],
      colors: {
        'editor.background': '#eff1f5',
        'editor.foreground': '#4c4f69',
        'editor.lineHighlightBackground': '#e6e9ef',
        'editorCursor.foreground': '#1e66f5',
        'editorLineNumber.foreground': '#9ca0b0',
        'editorLineNumber.activeForeground': '#7c7f93',
        'editor.selectionBackground': '#ccd0da',
        'editorIndentGuide.background': '#e6e9ef',
        'editorIndentGuide.activeBackground': '#d0d3db',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#9ca0b0',
      },
};
