export const catppuccinMacchiatoTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '6e738d', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'c6a0f6' },
        { token: 'string', foreground: 'a6da95' },
        { token: 'number', foreground: 'f4a8b8' },
        { token: 'type', foreground: 'eed49f' },
        { token: 'function', foreground: '8aadf4' },
        { token: 'variable', foreground: 'cad3f8' },
        { token: 'operator', foreground: '8bd5ca' },
        { token: 'delimiter', foreground: '8bd5ca' },
        { token: 'tag', foreground: 'ed8796' },
        { token: 'attribute.name', foreground: 'c6a0f6' },
        { token: 'attribute.value', foreground: 'a6da95' },
      ],
      colors: {
        'editor.background': '#24273a',
        'editor.foreground': '#cad3f8',
        'editor.lineHighlightBackground': '#303347',
        'editorCursor.foreground': '#8aadf4',
        'editorLineNumber.foreground': '#494d64',
        'editorLineNumber.activeForeground': '#5b6078',
        'editor.selectionBackground': '#363a4f',
        'editorIndentGuide.background': '#303347',
        'editorIndentGuide.activeBackground': '#3b3f54',
        'editorWidget.background': '#363a4f',
        'editorSuggestWidget.background': '#363a4f',
        'editorSuggestWidget.border': '#494d64',
      },
};
