export const catppuccinMacchiatoLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '7c7f93', fontStyle: 'italic' },
        { token: 'keyword', foreground: '7c4dff' },
        { token: 'string', foreground: '40a02b' },
        { token: 'number', foreground: 'fe640b' },
        { token: 'type', foreground: 'df8e1d' },
        { token: 'function', foreground: '2a6ef5' },
        { token: 'variable', foreground: '494d64' },
        { token: 'operator', foreground: '179299' },
        { token: 'delimiter', foreground: '179299' },
        { token: 'tag', foreground: 'd20f39' },
        { token: 'attribute.name', foreground: '7c4dff' },
        { token: 'attribute.value', foreground: '40a02b' },
      ],
      colors: {
        'editor.background': '#f0f1f5',
        'editor.foreground': '#494d64',
        'editor.lineHighlightBackground': '#e8e9ed',
        'editorCursor.foreground': '#2a6ef5',
        'editorLineNumber.foreground': '#9ca0b0',
        'editorLineNumber.activeForeground': '#7c7f93',
        'editor.selectionBackground': '#ced4da',
        'editorIndentGuide.background': '#e8e9ed',
        'editorIndentGuide.activeBackground': '#d0d3db',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#9ca0b0',
      },
};
