export const darkTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '546e7a', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'c792ea' },
        { token: 'string', foreground: 'c3e88d' },
        { token: 'number', foreground: 'f78c6c' },
        { token: 'type', foreground: 'ffcb6b' },
        { token: 'function', foreground: '82aaff' },
        { token: 'variable', foreground: 'eeffff' },
        { token: 'operator', foreground: '89ddff' },
        { token: 'delimiter', foreground: '89ddff' },
        { token: 'tag', foreground: 'f07178' },
        { token: 'attribute.name', foreground: 'c792ea' },
        { token: 'attribute.value', foreground: 'c3e88d' },
      ],
      colors: {
        'editor.background': '#0e1017',
        'editor.foreground': '#eeffff',
        'editor.lineHighlightBackground': '#141620',
        'editor.selectionBackground': '#4f8cff28',
        'editorCursor.foreground': '#4f8cff',
        'editorLineNumber.foreground': '#2a2e3a',
        'editorLineNumber.activeForeground': '#4a5060',
        'editor.inactiveSelectionBackground': '#4f8cff12',
        'editorIndentGuide.background': '#1a1e28',
        'editorIndentGuide.activeBackground': '#282d38',
        'editorBracketMatch.background': '#4f8cff18',
        'editorBracketMatch.border': '#4f8cff33',
        'editorGutter.background': '#0e1017',
        'scrollbar.shadow': '#0000',
        'scrollbarSlider.background': '#ffffff08',
        'scrollbarSlider.hoverBackground': '#ffffff14',
        'scrollbarSlider.activeBackground': '#ffffff20',
        'editorWidget.background': '#181b24',
        'editorSuggestWidget.background': '#181b24',
        'editorSuggestWidget.border': '#ffffff08',
        'editorSuggestWidget.selectedBackground': '#4f8cff18',
      },
};
