export const everforestLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '8d9ba5', fontStyle: 'italic' },
        { token: 'keyword', foreground: '9c6cc2' },
        { token: 'string', foreground: '93b259' },
        { token: 'number', foreground: 'c34043' },
        { token: 'type', foreground: 'b0863e' },
        { token: 'function', foreground: '93b259' },
        { token: 'variable', foreground: '5c6a72' },
        { token: 'operator', foreground: 'c34043' },
        { token: 'delimiter', foreground: 'c34043' },
        { token: 'tag', foreground: 'c34043' },
        { token: 'attribute.name', foreground: '9c6cc2' },
        { token: 'attribute.value', foreground: '93b259' },
      ],
      colors: {
        'editor.background': '#f3ead3',
        'editor.foreground': '#5c6a72',
        'editor.lineHighlightBackground': '#eae0c8',
        'editorCursor.foreground': '#93b259',
        'editorLineNumber.foreground': '#adb5b9',
        'editorLineNumber.activeForeground': '#8d9ba5',
        'editor.selectionBackground': '#d4d9c8',
        'editorIndentGuide.background': '#eae0c8',
        'editorIndentGuide.activeBackground': '#ddd8c0',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#adb5b9',
      },
};
