export const everforestTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '859289', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'd699b6' },
        { token: 'string', foreground: 'a7c080' },
        { token: 'number', foreground: 'e67e80' },
        { token: 'type', foreground: 'dbbc7f' },
        { token: 'function', foreground: 'a7c080' },
        { token: 'variable', foreground: 'd3c6aa' },
        { token: 'operator', foreground: 'e69875' },
        { token: 'delimiter', foreground: 'e69875' },
        { token: 'tag', foreground: 'e67e80' },
        { token: 'attribute.name', foreground: 'd699b6' },
        { token: 'attribute.value', foreground: 'a7c080' },
      ],
      colors: {
        'editor.background': '#2b3339',
        'editor.foreground': '#d3c6aa',
        'editor.lineHighlightBackground': '#374145',
        'editorCursor.foreground': '#a7c080',
        'editorLineNumber.foreground': '#5c6a64',
        'editorLineNumber.activeForeground': '#859289',
        'editor.selectionBackground': '#425047',
        'editorIndentGuide.background': '#374145',
        'editorIndentGuide.activeBackground': '#475050',
        'editorWidget.background': '#374145',
        'editorSuggestWidget.background': '#374145',
        'editorSuggestWidget.border': '#475050',
      },
};
