export const gruvboxLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '928374', fontStyle: 'italic' },
        { token: 'keyword', foreground: '8f3f71' },
        { token: 'string', foreground: '79740e' },
        { token: 'number', foreground: 'af3a03' },
        { token: 'type', foreground: 'b57614' },
        { token: 'function', foreground: 'af3a03' },
        { token: 'variable', foreground: '3c3836' },
        { token: 'operator', foreground: 'af3a03' },
        { token: 'delimiter', foreground: 'af3a03' },
        { token: 'tag', foreground: '9d0006' },
        { token: 'attribute.name', foreground: '8f3f71' },
        { token: 'attribute.value', foreground: '79740e' },
      ],
      colors: {
        'editor.background': '#fbf1c7',
        'editor.foreground': '#3c3836',
        'editor.lineHighlightBackground': '#f2e5bc',
        'editorCursor.foreground': '#af3a03',
        'editorLineNumber.foreground': '#928374',
        'editorLineNumber.activeForeground': '#665c54',
        'editor.selectionBackground': '#e8d5a3',
        'editorIndentGuide.background': '#f2e5bc',
        'editorIndentGuide.activeBackground': '#ebd6a0',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#928374',
      },
};
