export const gruvboxTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '665c54', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'fb4934' },
        { token: 'string', foreground: 'b8bb26' },
        { token: 'number', foreground: 'fe8019' },
        { token: 'type', foreground: 'fabd2f' },
        { token: 'function', foreground: 'fabd2f' },
        { token: 'variable', foreground: 'ebdbb2' },
        { token: 'operator', foreground: 'fe8019' },
        { token: 'delimiter', foreground: 'fe8019' },
        { token: 'tag', foreground: 'fb4934' },
        { token: 'attribute.name', foreground: 'fb4934' },
        { token: 'attribute.value', foreground: 'b8bb26' },
      ],
      colors: {
        'editor.background': '#282828',
        'editor.foreground': '#ebdbb2',
        'editor.lineHighlightBackground': '#32302f',
        'editorCursor.foreground': '#fe8019',
        'editorLineNumber.foreground': '#504945',
        'editorLineNumber.activeForeground': '#665c54',
        'editor.selectionBackground': '#3c3836',
        'editorIndentGuide.background': '#32302f',
        'editorIndentGuide.activeBackground': '#3c3836',
        'editorWidget.background': '#3c3836',
        'editorSuggestWidget.background': '#3c3836',
        'editorSuggestWidget.border': '#504945',
      },
};
