export const kanagawaLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '727169', fontStyle: 'italic' },
        { token: 'keyword', foreground: '7e6cd8' },
        { token: 'string', foreground: '6f894e' },
        { token: 'number', foreground: 'b98e3e' },
        { token: 'type', foreground: '7e6cd8' },
        { token: 'function', foreground: '7e6cd8' },
        { token: 'variable', foreground: '43433c' },
        { token: 'operator', foreground: '8a7b62' },
        { token: 'delimiter', foreground: '8a7b62' },
        { token: 'tag', foreground: 'c34043' },
        { token: 'attribute.name', foreground: '7e6cd8' },
        { token: 'attribute.value', foreground: '6f894e' },
      ],
      colors: {
        'editor.background': '#e8e3d5',
        'editor.foreground': '#43433c',
        'editor.lineHighlightBackground': '#ddd8c8',
        'editorCursor.foreground': '#7e6cd8',
        'editorLineNumber.foreground': '#9d9d93',
        'editorLineNumber.activeForeground': '#727169',
        'editor.selectionBackground': '#c8c3b5',
        'editorIndentGuide.background': '#ddd8c8',
        'editorIndentGuide.activeBackground': '#d0ccb8',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#9d9d93',
      },
};
