export const kanagawaTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '727169', fontStyle: 'italic' },
        { token: 'keyword', foreground: '957fb8' },
        { token: 'string', foreground: '76946a' },
        { token: 'number', foreground: 'e6c384' },
        { token: 'type', foreground: '7e9cd8' },
        { token: 'function', foreground: '7e9cd8' },
        { token: 'variable', foreground: 'dcd7ba' },
        { token: 'operator', foreground: 'c0a36e' },
        { token: 'delimiter', foreground: 'c0a36e' },
        { token: 'tag', foreground: 'c34043' },
        { token: 'attribute.name', foreground: '957fb8' },
        { token: 'attribute.value', foreground: '76946a' },
      ],
      colors: {
        'editor.background': '#1f1f28',
        'editor.foreground': '#dcd7ba',
        'editor.lineHighlightBackground': '#2a2a37',
        'editorCursor.foreground': '#7e9cd8',
        'editorLineNumber.foreground': '#2a2a37',
        'editorLineNumber.activeForeground': '#54546d',
        'editor.selectionBackground': '#2a2a37',
        'editorIndentGuide.background': '#2a2a37',
        'editorIndentGuide.activeBackground': '#363646',
        'editorWidget.background': '#2a2a37',
        'editorSuggestWidget.background': '#2a2a37',
        'editorSuggestWidget.border': '#363646',
      },
};
