export const lightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '6a737d', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'd73a49' },
        { token: 'string', foreground: '032f62' },
        { token: 'number', foreground: '005cc5' },
        { token: 'type', foreground: 'e36209' },
        { token: 'function', foreground: '6f42c1' },
        { token: 'variable', foreground: '24292e' },
        { token: 'operator', foreground: 'd73a49' },
        { token: 'delimiter', foreground: '24292e' },
        { token: 'tag', foreground: '22863a' },
        { token: 'attribute.name', foreground: '6f42c1' },
        { token: 'attribute.value', foreground: '032f62' },
      ],
      colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#24292e',
        'editor.lineHighlightBackground': '#f6f8fa',
        'editor.selectionBackground': '#4f8cff28',
        'editorCursor.foreground': '#3b82f6',
        'editorLineNumber.foreground': '#babbbd',
        'editorLineNumber.activeForeground': '#24292e',
        'editor.inactiveSelectionBackground': '#4f8cff12',
        'editorIndentGuide.background': '#eff2f5',
        'editorIndentGuide.activeBackground': '#d1d5da',
        'editorBracketMatch.background': '#4f8cff18',
        'editorBracketMatch.border': '#4f8cff33',
        'editorGutter.background': '#ffffff',
        'scrollbar.shadow': '#0000',
        'scrollbarSlider.background': '#00000012',
        'scrollbarSlider.hoverBackground': '#00000020',
        'scrollbarSlider.activeBackground': '#00000030',
        'editorWidget.background': '#f6f8fa',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#e1e4e8',
        'editorSuggestWidget.selectedBackground': '#4f8cff18',
      },
};
