export const matrixTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '006619', fontStyle: 'italic' },
        { token: 'keyword', foreground: '00ff41' },
        { token: 'string', foreground: '33ff66' },
        { token: 'number', foreground: '00ff41' },
        { token: 'type', foreground: '00cc33' },
        { token: 'function', foreground: '00ff41' },
        { token: 'variable', foreground: '00ff41' },
        { token: 'operator', foreground: '00ff41' },
        { token: 'delimiter', foreground: '00ff41' },
        { token: 'tag', foreground: '00ff41' },
        { token: 'attribute.name', foreground: '00cc33' },
        { token: 'attribute.value', foreground: '33ff66' },
      ],
      colors: {
        'editor.background': '#0a0a0a',
        'editor.foreground': '#00ff41',
        'editor.lineHighlightBackground': '#0d0d0d',
        'editorCursor.foreground': '#00ff41',
        'editorLineNumber.foreground': '#00330d',
        'editorLineNumber.activeForeground': '#006619',
        'editor.selectionBackground': '#00330d',
        'editorIndentGuide.background': '#0d0d0d',
        'editorIndentGuide.activeBackground': '#141414',
        'editorWidget.background': '#141414',
        'editorSuggestWidget.background': '#141414',
        'editorSuggestWidget.border': '#00330d',
      },
};
