export const matrixLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '3d8a3d', fontStyle: 'italic' },
        { token: 'keyword', foreground: '1a6b1a' },
        { token: 'string', foreground: '2d6b2d' },
        { token: 'number', foreground: '1a8b1a' },
        { token: 'type', foreground: '2d7a2d' },
        { token: 'function', foreground: '1a8b1a' },
        { token: 'variable', foreground: '1a4a1a' },
        { token: 'operator', foreground: '1a8b1a' },
        { token: 'delimiter', foreground: '1a8b1a' },
        { token: 'tag', foreground: '1a6b1a' },
        { token: 'attribute.name', foreground: '2d7a2d' },
        { token: 'attribute.value', foreground: '2d6b2d' },
      ],
      colors: {
        'editor.background': '#e8efe8',
        'editor.foreground': '#1a4a1a',
        'editor.lineHighlightBackground': '#dce5dc',
        'editorCursor.foreground': '#1a8b1a',
        'editorLineNumber.foreground': '#6aad6a',
        'editorLineNumber.activeForeground': '#3d8a3d',
        'editor.selectionBackground': '#b0ddb0',
        'editorIndentGuide.background': '#dce5dc',
        'editorIndentGuide.activeBackground': '#d0d8d0',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#6aad6a',
      },
};
