export const nordTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '616e88', fontStyle: 'italic' },
        { token: 'keyword', foreground: '81a1c1' },
        { token: 'string', foreground: 'a3be8c' },
        { token: 'number', foreground: 'b48ead' },
        { token: 'type', foreground: '8fbcbb' },
        { token: 'function', foreground: '88c0d0' },
        { token: 'variable', foreground: 'd8dee9' },
        { token: 'operator', foreground: '81a1c1' },
        { token: 'delimiter', foreground: '81a1c1' },
        { token: 'tag', foreground: '81a1c1' },
        { token: 'attribute.name', foreground: 'b48ead' },
        { token: 'attribute.value', foreground: 'a3be8c' },
      ],
      colors: {
        'editor.background': '#2e3440',
        'editor.foreground': '#d8dee9',
        'editor.lineHighlightBackground': '#3b4252',
        'editorCursor.foreground': '#88c0d0',
        'editorLineNumber.foreground': '#4c566a',
        'editorLineNumber.activeForeground': '#616e88',
        'editor.selectionBackground': '#3b4252',
        'editorIndentGuide.background': '#3b4252',
        'editorIndentGuide.activeBackground': '#434c5e',
        'editorWidget.background': '#3b4252',
        'editorSuggestWidget.background': '#3b4252',
        'editorSuggestWidget.border': '#4c566a',
      },
};
