export const nordLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '81a1c1', fontStyle: 'italic' },
        { token: 'keyword', foreground: '5e81ac' },
        { token: 'string', foreground: 'a3be8c' },
        { token: 'number', foreground: 'b48ead' },
        { token: 'type', foreground: '8fbcbb' },
        { token: 'function', foreground: '5e81ac' },
        { token: 'variable', foreground: '2e3440' },
        { token: 'operator', foreground: '81a1c1' },
        { token: 'delimiter', foreground: '81a1c1' },
        { token: 'tag', foreground: 'bf616a' },
        { token: 'attribute.name', foreground: 'b48ead' },
        { token: 'attribute.value', foreground: 'a3be8c' },
      ],
      colors: {
        'editor.background': '#eceff4',
        'editor.foreground': '#2e3440',
        'editor.lineHighlightBackground': '#e5e9f0',
        'editorCursor.foreground': '#5e81ac',
        'editorLineNumber.foreground': '#b0b8c4',
        'editorLineNumber.activeForeground': '#81a1c1',
        'editor.selectionBackground': '#d8dee9',
        'editorIndentGuide.background': '#e5e9f0',
        'editorIndentGuide.activeBackground': '#d8dee9',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#b0b8c4',
      },
};
