export const oneDarkLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '6a6b78', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'a626a4' },
        { token: 'string', foreground: '50a14f' },
        { token: 'number', foreground: '986801' },
        { token: 'type', foreground: 'c18401' },
        { token: 'function', foreground: '4078f2' },
        { token: 'variable', foreground: 'e45649' },
        { token: 'operator', foreground: '0184bc' },
        { token: 'delimiter', foreground: '0184bc' },
        { token: 'tag', foreground: 'e45649' },
        { token: 'attribute.name', foreground: '986801' },
        { token: 'attribute.value', foreground: '50a14f' },
      ],
      colors: {
        'editor.background': '#fafafa',
        'editor.foreground': '#383a42',
        'editor.lineHighlightBackground': '#f0f0f0',
        'editorCursor.foreground': '#4078f2',
        'editorLineNumber.foreground': '#9da5b4',
        'editorLineNumber.activeForeground': '#6a6b78',
        'editor.selectionBackground': '#e5e8ec',
        'editorIndentGuide.background': '#f0f0f0',
        'editorIndentGuide.activeBackground': '#e6e6e6',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#9da5b4',
      },
};
