export const oneDarkTheme = {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'c678dd' },
        { token: 'string', foreground: '98c379' },
        { token: 'number', foreground: 'd19a66' },
        { token: 'type', foreground: 'e5c07b' },
        { token: 'function', foreground: '61afef' },
        { token: 'variable', foreground: 'e06c75' },
        { token: 'operator', foreground: '56b6c2' },
        { token: 'delimiter', foreground: '56b6c2' },
        { token: 'tag', foreground: 'e06c75' },
        { token: 'attribute.name', foreground: 'd19a66' },
        { token: 'attribute.value', foreground: '98c379' },
      ],
      colors: {
        'editor.background': '#282c34',
        'editor.foreground': '#abb2bf',
        'editor.lineHighlightBackground': '#2c313c',
        'editorCursor.foreground': '#528bff',
        'editorLineNumber.foreground': '#4b5263',
        'editorLineNumber.activeForeground': '#636d83',
        'editor.selectionBackground': '#3e4451',
        'editorIndentGuide.background': '#2c313c',
        'editorIndentGuide.activeBackground': '#3e4451',
        'editorWidget.background': '#2c313c',
        'editorSuggestWidget.background': '#2c313c',
        'editorSuggestWidget.border': '#4b5263',
      },
};
