export const tokyonightLightTheme = {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '68709a', fontStyle: 'italic' },
        { token: 'keyword', foreground: '9854f1' },
        { token: 'string', foreground: '587539' },
        { token: 'number', foreground: 'e0584e' },
        { token: 'type', foreground: '2e7de9' },
        { token: 'function', foreground: '2e7de9' },
        { token: 'variable', foreground: '3760bf' },
        { token: 'operator', foreground: '587539' },
        { token: 'delimiter', foreground: '587539' },
        { token: 'tag', foreground: 'f52a65' },
        { token: 'attribute.name', foreground: '9854f1' },
        { token: 'attribute.value', foreground: '587539' },
      ],
      colors: {
        'editor.background': '#e1e2e7',
        'editor.foreground': '#3760bf',
        'editor.lineHighlightBackground': '#e9e9ed',
        'editorCursor.foreground': '#2e7de9',
        'editorLineNumber.foreground': '#a8aecb',
        'editorLineNumber.activeForeground': '#68709a',
        'editor.selectionBackground': '#b6c8f5',
        'editorIndentGuide.background': '#c4c8d4',
        'editorIndentGuide.activeBackground': '#b4bcbd',
        'editorWidget.background': '#ffffff',
        'editorSuggestWidget.background': '#ffffff',
        'editorSuggestWidget.border': '#a8aecb',
      },
};
