import type { EditorSettings } from '../../types';
import { defaultKeybindings } from '../keybindings/defaultKeybindings';

export const defaultSettings: EditorSettings = {
  fontSize: 13,
  tabSize: 2,
  wordWrap: true,
  minimap: false,
  stickyScroll: true,
  autoSaveDelay: 1000,
  autoSaveOnFocusChange: false,
  fontLigatures: true,
  lineNumbers: true,
  cursorBlinking: 'smooth',
  fontFamily: 'JetBrains Mono',
  cursorStyle: 'line',
  renderWhitespace: 'none',
  bracketPairColorization: true,
  autoClosingBrackets: true,
  smoothScrolling: true,
  tailwindTooling: true,
  tailwindClassSorting: true,
  webWorkflowPreviewBehavior: 'ask',
  webWorkflowMode: 'guided',
  aiInlineCompletions: true,
  gitInlineBlame: true,
  envMaskSecrets: true,
  spellChecker: false,
  snippets: [],
  importedTheme: null,
  trimTrailingWhitespace: false,
  insertFinalNewline: true,
  insertSpaces: true,
  animations: true,
  showFileIcons: true,
  compactMode: false,
  uiDensity: 'default',
  uiScale: 100,
  explorerRowHeight: 24,
  activityBarOrder: ['explorer', 'search', 'sourceControl', 'debug', 'npmScripts'],
  hiddenActivityBarItems: [],
  panelWidths: {
    explorer: 250,
    search: 300,
    sourceControl: 300,
    debug: 320,
    extensions: 300,
    npmScripts: 320,
  },
  bottomPanelPosition: 'bottom',
  bottomPanelWidth: 440,
  dotGridColor: '#4f8cff',
  backgroundStyle: 'dotgrid',
  editorBackgroundPreset: 'none',
  editorBackgroundCustom: null,
  editorBackgroundOpacity: 18,
  editorBackgroundBlur: 0,
  editorBackgroundScale: 102,
  editorBackgroundBrightness: 90,
  keybindings: defaultKeybindings,
  language: 'en',
  colorScheme: 'dark',
  theme: 'one-dark',
};
