import { defineBlinkTheme } from './defineBlinkTheme';
import { darkTheme } from './themeDefinitions/darkTheme';
import { lightTheme } from './themeDefinitions/lightTheme';
import { tokyonightTheme } from './themeDefinitions/tokyonightTheme';
import { tokyonightLightTheme } from './themeDefinitions/tokyonightLightTheme';
import { everforestTheme } from './themeDefinitions/everforestTheme';
import { everforestLightTheme } from './themeDefinitions/everforestLightTheme';
import { ayuTheme } from './themeDefinitions/ayuTheme';
import { ayuLightTheme } from './themeDefinitions/ayuLightTheme';
import { catppuccinTheme } from './themeDefinitions/catppuccinTheme';
import { catppuccinLightTheme } from './themeDefinitions/catppuccinLightTheme';
import { catppuccinMacchiatoTheme } from './themeDefinitions/catppuccinMacchiatoTheme';
import { catppuccinMacchiatoLightTheme } from './themeDefinitions/catppuccinMacchiatoLightTheme';
import { gruvboxTheme } from './themeDefinitions/gruvboxTheme';
import { gruvboxLightTheme } from './themeDefinitions/gruvboxLightTheme';
import { kanagawaTheme } from './themeDefinitions/kanagawaTheme';
import { kanagawaLightTheme } from './themeDefinitions/kanagawaLightTheme';
import { nordTheme } from './themeDefinitions/nordTheme';
import { nordLightTheme } from './themeDefinitions/nordLightTheme';
import { matrixTheme } from './themeDefinitions/matrixTheme';
import { matrixLightTheme } from './themeDefinitions/matrixLightTheme';
import { oneDarkTheme } from './themeDefinitions/oneDarkTheme';
import { oneDarkLightTheme } from './themeDefinitions/oneDarkLightTheme';
import { amoledTheme } from './themeDefinitions/amoledTheme';
import { amoledLightTheme } from './themeDefinitions/amoledLightTheme';
import { registerImportedTheme } from './registerImportedTheme';
import type { ImportedTheme } from '../../types';

export function registerBlinkThemes(monaco: any, importedTheme?: ImportedTheme | null): void {
  defineBlinkTheme(monaco, 'blinkcode-dark', darkTheme);
  defineBlinkTheme(monaco, 'blinkcode-light', lightTheme);
  defineBlinkTheme(monaco, 'blinkcode-tokyonight', tokyonightTheme);
  defineBlinkTheme(monaco, 'blinkcode-tokyonight-light', tokyonightLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-everforest', everforestTheme);
  defineBlinkTheme(monaco, 'blinkcode-everforest-light', everforestLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-ayu', ayuTheme);
  defineBlinkTheme(monaco, 'blinkcode-ayu-light', ayuLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-catppuccin', catppuccinTheme);
  defineBlinkTheme(monaco, 'blinkcode-catppuccin-light', catppuccinLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-catppuccin-macchiato', catppuccinMacchiatoTheme);
  defineBlinkTheme(monaco, 'blinkcode-catppuccin-macchiato-light', catppuccinMacchiatoLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-gruvbox', gruvboxTheme);
  defineBlinkTheme(monaco, 'blinkcode-gruvbox-light', gruvboxLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-kanagawa', kanagawaTheme);
  defineBlinkTheme(monaco, 'blinkcode-kanagawa-light', kanagawaLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-nord', nordTheme);
  defineBlinkTheme(monaco, 'blinkcode-nord-light', nordLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-matrix', matrixTheme);
  defineBlinkTheme(monaco, 'blinkcode-matrix-light', matrixLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-one-dark', oneDarkTheme);
  defineBlinkTheme(monaco, 'blinkcode-one-dark-light', oneDarkLightTheme);
  defineBlinkTheme(monaco, 'blinkcode-amoled', amoledTheme);
  defineBlinkTheme(monaco, 'blinkcode-amoled-light', amoledLightTheme);
  registerImportedTheme(monaco, importedTheme || null);
}
